# Generated by Django 3.1.4 on 2021-01-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drlevel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldevice',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='manufacture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='model_device',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
