# Generated by Django 3.1.4 on 2021-01-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerlevel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldevice',
            name='Department_of_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='managerlevel.departments'),
        ),
    ]
