# Generated by Django 3.1.4 on 2021-02-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerlevel', '0003_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='Case',
            field=models.BooleanField(blank=True, max_length=250, null=True),
        ),
    ]
