# Generated by Django 3.1.4 on 2021-02-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerlevel', '0004_auto_20210202_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='Equipment',
            new_name='equipment',
        ),
    ]
