# Generated by Django 3.1.4 on 2021-02-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerlevel', '0005_auto_20210202_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='equipment',
            new_name='name',
        ),
    ]
