# Generated by Django 3.1.4 on 2021-02-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerlevel', '0006_auto_20210202_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='name',
            new_name='Equipment',
        ),
    ]
